### ISSUE TITLE
Tiếng Việt trong Oracle

### ISSUE THREAD

**Issue by leanhboi1999** [TranXuanHanh/LibraryManagementSystem-NT718#1]
Làm sao để anh có thể insert tiếng Việt trong Oracle 12c

**Comment by hanhtxz** [comment]
Anh insert bình thường em ơi, chỉ có SQLPlus là insert không được vì không cho gõ tiếng Việt thôi em. 
Em thử vào SQL Developer rồi vào Preference, chọn Environment rồi chọn Encoding UTF-8 thử coi.

**Comment by leanhboi1999** [comment]
Cảm ơn anh, em tìm ra cái này rồi. Tại lúc cài em quên mất vụ set character UTF-8. Mà cái issue này em close được đúng không anh, em chưa xài mấy đoạn này.
